# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc0b5e956ea7ea3d339880528ded81d610036a17955bec1bc3725fab498a60ff09c0efcf9bc1d06170d652cd9fc9efe7f22277ca197c7b8964ffadbf3b5b6713

test:
  secret_key_base: 2705ce801d83c5a7a8b8811ab9be0d4efb89b9a42a8d29fa10177a6e443ff6e49f5c89c1cb7a3ca4932996c168561ad5b29fc4f01f507f1986f83debf87133c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
